### ISSUE TITLE
Difficulty Setting Up Plugins for Auto-GPT in Docker on Arch Linux

### ISSUE THREAD

**Issue by Kozyge** [Significant-Gravitas/Auto-GPT-Plugins#235]
I am experiencing difficulty in setting up plugins for Auto-GPT when running it through Docker on my Arch Linux system. Despite following existing documentation and related issue threads, I haven't been successful in getting the plugins to work.
Environment

    Operating System: Arch Linux
    Docker Version: Docker version 24.0.6

Steps to Reproduce

I read through the issue [#185](https://github.com/Significant-Gravitas/Auto-GPT-Plugins/issues/185) on the Auto-GPT-Plugins repository but found that none of the resolutions there helped.
I attempted to integrate plugins with Auto-GPT using the following method:
       
Edited my docker-compose.yaml file as follows:

```
version: "3.9"
services:
  auto-gpt:
    image: significantgravitas/auto-gpt
    env_file:
      - .env
    profiles: ["exclude-from-up"]
    volumes:
      - ./auto_gpt_workspace:/app/auto_gpt_workspace
      - ./data:/app/data
      - ./logs:/app/logs
      - ./plugins:/app/plugins


```

    Ran the command mkdir ./plugins && curl -L -o ./plugins/Auto-GPT-Plugins.zip https://github.com/Significant-Gravitas/Auto-GPT-Plugins/archive/refs/heads/master.zip in the directory to fetch and unzip the plugin.

I extracted the contents of Auto-GPT-Plugins.zip into the ./plugins directory.
Created a plugins_config.yaml in the appropriate directory.

Expected Behavior

I expected that after setting up the plugins directory and the plugins_config.yaml, Auto-GPT would recognize and load the plugins upon startup.
Actual Behavior

The application does not seem to recognize or load the plugins_config.yaml. It behaves as if the plugin configuration file is not present.
Additional Context

    I have checked the permissions of the plugins_config.yaml to ensure it's readable.
    There are no apparent error messages related to plugin loading in the logs.
    I tried restarting Docker and re-running the setup steps.
